apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-jfhq
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-prih-tenant/rhtap-demo-app/hacbs-test-project-jfhq@sha256:767d10f21f0d1bd71560df1df244180d91fc92495fa2fba51336fad0f13889ad
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
