apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-jfhq
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-prih-tenant/rhtap-demo-app/hacbs-test-project-jfhq@sha256:4335f77a15879df22789b2e617dea93dd870317b16d8f7fb63ea458fbf549a98
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
