apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-jfhq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-jfhq
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-jfhq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-jfhq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-jfhq
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-prih-tenant/rhtap-demo-app/hacbs-test-project-jfhq@sha256:cd43f42eb085dad6004c7d809e435ca5381df26c839d08aeb6c1f6976413d6ac
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
